"""empty message

Revision ID: 720e689a0af7
Revises: c16baac973ba
Create Date: 2025-10-04 02:58:05.240196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '720e689a0af7'
down_revision = 'c16baac973ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_list', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
        batch_op.drop_column('type')

    # ### end Alembic commands ###
