"""empty message

Revision ID: c16baac973ba
Revises: 
Create Date: 2025-10-01 01:34:39.049375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16baac973ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_inform', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_list', schema=None) as batch_op:
        batch_op.drop_column('date_inform')

    # ### end Alembic commands ###
